### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Werneq** [bhaan23/Path-of-Progression#2]
**Minor bug**
On Create Progression:

1. Add a new node
2. Select the trigger "Link Gems"
3. Select some gems
4. Swap the trigger for "Enter area".

Gems will keep showing on node.

**The following is not a bug, but would be nice to have.**

- Allow to window be resized to lower sizes, to fit well on small monitors
- Make it overlay, or just always on top, for people that like to play on full screen.

**Comment by bhaan23** [comment]
Fixed the issue with the gems sticking around. That should be in the next patch. 

As for the window resizing: How small are we talking here? I currently have the minimum set at 600x850.

And an overlay now exists.

**Comment by Werneq** [comment]
I think just that margins solve the problem (img1).
But if only the nodes shows on screen, maybe a "lite" version only for visualize the progression, with some controls like close the next node... (img2)

**Img1**
![image](https://user-images.githubusercontent.com/47800790/53064197-befcd680-34a5-11e9-9bce-3ab9963ea70c.png)


**Img2**
![image](https://user-images.githubusercontent.com/47800790/53064535-ec964f80-34a6-11e9-9d09-884f28f5dabf.png)

**Comment by Werneq** [comment]
NVM, I just receive the new version, loved the pop up.
Just some QoL adjustment like the contrast between red text and the background.

White edge on text do the job
![image](https://user-images.githubusercontent.com/47800790/53064687-7fcf8500-34a7-11e9-9133-2891b8b9dc03.png)

**Comment by bhaan23** [comment]
Thanks, I will be continuing to improve that overlay, as it seems to be the thing people are most concerned about at the moment.
